nome = input('Entre com o nome: ')
matricula = int(input('Entre com a matrícula: '))
curso = input('Entre com o seu curso: ')
idade = int(input('Entre com a sua idade: '))
email = input('Digite seu email: ')

print('Nome: ', nome)
print('matrícula: ', matricula)
print('Curso: ', curso)
print('Idade: ', idade)
print('Email: ', email)